arranger: formatting imports in arranger javascript

diff --git a/format b/format
--- a/format
+++ b/format
@@ -13,12 +13,16 @@ cd "$(git rev-parse --show-toplevel)"
     apps/interactor/tests
 
 if ! which prettier >/dev/null; then
-  echo "Couldn't find prettier, not formatting javascript files"
+    echo "Couldn't find prettier, not formatting javascript files"
 else
-  echo ""
-  echo "==="
-  echo "--- Formatting javascript"
-  echo "==="
-  echo ""
-  prettier --write "apps/arranger/arranger/static/js/**"
+    echo ""
+    echo "==="
+    echo "--- Formatting javascript"
+    echo "==="
+    echo ""
+    if ! npm list -g | grep prettier-plugin-organize-imports >/dev/null; then
+        npm install -g prettier-plugin-organize-imports
+    fi
+
+    prettier --write "apps/arranger/arranger/static/js/**"
 fi
