[photons_canvas] Replacing themes/tile_paint with new code
The tile animations have been rewritten from the ground up.

The photons_themes and photons_tile_paint modules have been replaced
with the photons_canvas module.

``ApplyTheme`` is now under ``photons_canvas.ApplyTheme``.

The programmatic and cli interface to animations is entirely different
and will be explained in the documentation.

The animations are now more capable, flexible and look a bit better.

Two new gatherer plans have been introduced: ``parts`` and
``parts_with_colors``. These return ``photons_canvas.points.containers.Part``
objects which represent a single item in a chain. Devices that don't have
chains (bulbs and strips) are represented as a single Part. The ``with_colors``
plan will also record the current state of the device in the part object.

diff --git a/format b/format
--- a/format
+++ b/format
@@ -4,4 +4,15 @@ cd $(git rev-parse --show-toplevel)
 
 ./tools/black/setup_venv
 
-./tools/black/.black/bin/noy_black .
+./tools/black/.black/bin/noy_black modules apps/arranger/arranger
+
+if ! which prettier >/dev/null; then
+  echo "Couldn't find prettier, not formatting javascript files"
+else
+  echo ""
+  echo "==="
+  echo "--- Formatting javascript"
+  echo "==="
+  echo ""
+  prettier --write "apps/arranger/arranger/static/js/**"
+fi
