[arranger] generate assets better

diff --git a/.github/workflows/release-arranger.yml b/.github/workflows/release-arranger.yml
--- a/.github/workflows/release-arranger.yml
+++ b/.github/workflows/release-arranger.yml
@@ -26,8 +26,13 @@ jobs:
           python3 -m venv /tmp/photons
           /tmp/photons/bin/python -m pip install -e modules
           /tmp/photons/bin/python -m pip install -e apps/arranger
-          yarn add webpack-cli
+          yarn add webpack-cli webpack
           NODE_ENV=production /tmp/photons/bin/lifx arranger_assets static
+          if ! ls apps/arranger/arranger/static/dist/prod/static/*.js > /dev/null; then
+            ls -R apps/arranger/arranger/static/dist/prod
+            echo "Couldn't find any javascript!"
+            exit 1
+          fi
 
       - id: see_built_assets
         run: ls -R apps/arranger/arranger/static/dist
